version: "3"
services:
  tickets-api:
    image: node:13.8.0-alpine3.11
    volumes:
      - applications-docker-sync:/usr/tickets-api:nocopy
    ports:
      - 4000:4000
    working_dir: /usr/tickets-api
    command: yarn dev

  mongo:
    image: mongo:4.2.5
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=db
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

volumes:
  applications-docker-sync:
    external: true
